resolver: lts-7.19
packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []

# compiler: ghcjs-0.1.0.20150924_ghc-7.10.2
# compiler: ghcjs

resolver: lts-7.15
compiler: ghcjs-0.2.1.9007015_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007015_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-01-11-lts-7.15-9007015.tar.gz
           sha1: 30d34e9d704bdb799066387dfa1ba98b8884d932
